artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Madhuvamsi-iitg/images-for-chicken-disease-/raw/main/chicken-fecal-images%20(2).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion 
